{% set name = "e3sm_diags" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/E3SM-Project/e3sm_diags/archive/v{{ version }}.tar.gz
  sha256: cd4651e4f45a956e5f55555e813b166cd37d04689dbc56fdb2c2b7e2540245c6
  patches:
    - 0001-Disable-failing-tests.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - e3sm_diags = acme_diags.acme_diags_driver:main
    - acme_diags = acme_diags.acme_diags_driver:main
    - e3sm_diags_vars = acme_diags.acme_diags_vars:main

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - cdp >=1.7.0
    - cdms2
    - cdutil
    - genutil
    - cdtime
    - numpy
    - matplotlib-base
    - cartopy
    - beautifulsoup4
    - lxml
    - dask
    - scipy
    - output_viewer 1.3.1

test:
  source_files:
    - tests/*
  imports:
    - acme_diags
  commands:
    - e3sm_diags --help
    - cd tests/system && python -m unittest
    - cd tests && python -m unittest

about:
  home: https://github.com/E3SM-Project/e3sm_diags
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    Diagnostics package for the DOE's Energy Exascale Earth System Model
    (E3SM) project.
  doc_url: https://e3sm-project.github.io/e3sm_diags/docs/html/index.html
  dev_url: https://github.com/E3SM-Project/e3sm_diags

extra:
  recipe-maintainers:
    - xylar
    - chengzhuzhang
    - forsyth2
